[workspace]
resolver = "2"
members = ["xchange-fw", "xchange-scsi", "xchange-cli", "xchange-ublk", "xchange-nbd", "xchange-conform"]

[workspace.package]
version = "0.1.0"
edition = "2021"
license = "GPL-2.0-only"
authors = ["Adam Leyshon <aleyshon@thecodecache.net>"]

[workspace.dependencies]
nusb = "0.2.7"
thiserror = "2"
clap = { version = "4", features = ["derive"] }
sha2 = "0.10"
